/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_midway_MidWay */

#ifndef _Included_org_midway_MidWay
#define _Included_org_midway_MidWay
#ifdef __cplusplus
extern "C" {
#endif
#undef org_midway_MidWay_FAIL
#define org_midway_MidWay_FAIL 0L
#undef org_midway_MidWay_SUCCESS
#define org_midway_MidWay_SUCCESS 1L
#undef org_midway_MidWay_MORE
#define org_midway_MidWay_MORE 2L
#undef org_midway_MidWay_NOREPLY
#define org_midway_MidWay_NOREPLY 1L
#undef org_midway_MidWay_NOBLOCK
#define org_midway_MidWay_NOBLOCK 2L
#undef org_midway_MidWay_NOTIME
#define org_midway_MidWay_NOTIME 4L
#undef org_midway_MidWay_SIGRST
#define org_midway_MidWay_SIGRST 8L
#undef org_midway_MidWay_NOTRAN
#define org_midway_MidWay_NOTRAN 16L
#undef org_midway_MidWay_UNIQUE
#define org_midway_MidWay_UNIQUE 32L
#undef org_midway_MidWay_MULTIPLE
#define org_midway_MidWay_MULTIPLE 64L
#undef org_midway_MidWay_IPCONLY
#define org_midway_MidWay_IPCONLY 128L
#undef org_midway_MidWay_CONV
#define org_midway_MidWay_CONV 65536L
#undef org_midway_MidWay_STDIO
#define org_midway_MidWay_STDIO 131072L
#undef org_midway_MidWay_EVSTRING
#define org_midway_MidWay_EVSTRING 0L
#undef org_midway_MidWay_EVGLOB
#define org_midway_MidWay_EVGLOB 1048576L
#undef org_midway_MidWay_EVREGEXP
#define org_midway_MidWay_EVREGEXP 2097152L
#undef org_midway_MidWay_EVEREGEXP
#define org_midway_MidWay_EVEREGEXP 4194304L
#undef org_midway_MidWay_CLIENT
#define org_midway_MidWay_CLIENT 0L
#undef org_midway_MidWay_NOTCLIENT
#define org_midway_MidWay_NOTCLIENT 16777216L
#undef org_midway_MidWay_SERVER
#define org_midway_MidWay_SERVER 33554432L
#undef org_midway_MidWay_SERVERONLY
#define org_midway_MidWay_SERVERONLY 50331648L
#undef org_midway_MidWay_GATEWAY
#define org_midway_MidWay_GATEWAY 67108864L
#undef org_midway_MidWay_AUTH_NONE
#define org_midway_MidWay_AUTH_NONE 0L
#undef org_midway_MidWay_AUTH_PASSWORD
#define org_midway_MidWay_AUTH_PASSWORD 1L
#undef org_midway_MidWay_AUTH_X509
#define org_midway_MidWay_AUTH_X509 2L
#undef org_midway_MidWay_AUTH_KRB5
#define org_midway_MidWay_AUTH_KRB5 3L
#undef org_midway_MidWay_LOG_FATAL
#define org_midway_MidWay_LOG_FATAL 0L
#undef org_midway_MidWay_LOG_ERROR
#define org_midway_MidWay_LOG_ERROR 1L
#undef org_midway_MidWay_LOG_WARNING
#define org_midway_MidWay_LOG_WARNING 2L
#undef org_midway_MidWay_LOG_ALERT
#define org_midway_MidWay_LOG_ALERT 3L
#undef org_midway_MidWay_LOG_INFO
#define org_midway_MidWay_LOG_INFO 4L
#undef org_midway_MidWay_LOG_DEBUG
#define org_midway_MidWay_LOG_DEBUG 5L
#undef org_midway_MidWay_LOG_DEBUG1
#define org_midway_MidWay_LOG_DEBUG1 6L
#undef org_midway_MidWay_LOG_DEBUG2
#define org_midway_MidWay_LOG_DEBUG2 7L
#undef org_midway_MidWay_LOG_DEBUG3
#define org_midway_MidWay_LOG_DEBUG3 8L
#undef org_midway_MidWay_LOG_DEBUG4
#define org_midway_MidWay_LOG_DEBUG4 9L
/*
 * Class:     org_midway_MidWay
 * Method:    attach
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_midway_MidWay_attach
  (JNIEnv *, jclass, jstring, jstring, jint);

/*
 * Class:     org_midway_MidWay
 * Method:    detach
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_midway_MidWay_detach
  (JNIEnv *, jclass);

/*
 * Class:     org_midway_MidWay
 * Method:    getURL
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_midway_MidWay_getURL
  (JNIEnv *, jclass);

/*
 * Class:     org_midway_MidWay
 * Method:    listServices
 * Signature: (Ljava/lang/String;)[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_midway_MidWay_listServices
  (JNIEnv *, jclass, jstring);

/*
 * Class:     org_midway_MidWay
 * Method:    acall
 * Signature: (Ljava/lang/String;[BI)I
 */
JNIEXPORT jint JNICALL Java_org_midway_MidWay_acall
  (JNIEnv *, jclass, jstring, jbyteArray, jint);

/*
 * Class:     org_midway_MidWay
 * Method:    fetch
 * Signature: (ILorg/midway/CallReply;I)Z
 */
JNIEXPORT jboolean JNICALL Java_org_midway_MidWay_fetch
  (JNIEnv *, jclass, jint, jobject, jint);

/*
 * Class:     org_midway_MidWay
 * Method:    provide
 * Signature: (Ljava/lang/String;Lorg/midway/ServiceProvider;)I
 */
JNIEXPORT jint JNICALL Java_org_midway_MidWay_provide
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     org_midway_MidWay
 * Method:    unprovide
 * Signature: (Ljava/lang/String;J)I
 */
JNIEXPORT jint JNICALL Java_org_midway_MidWay_unprovide
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     org_midway_MidWay
 * Method:    forward
 * Signature: (Ljava/lang/String;[B)I
 */
JNIEXPORT jint JNICALL Java_org_midway_MidWay_forward
  (JNIEnv *, jclass, jstring, jbyteArray);

/*
 * Class:     org_midway_MidWay
 * Method:    reply
 * Signature: ([BII)I
 */
JNIEXPORT jint JNICALL Java_org_midway_MidWay_reply
  (JNIEnv *, jclass, jbyteArray, jint, jint);

/*
 * Class:     org_midway_MidWay
 * Method:    doServiceRequest
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_midway_MidWay_doServiceRequest
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_midway_MidWay
 * Method:    event
 * Signature: (Ljava/lang/String;[BLjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_midway_MidWay_event
  (JNIEnv *, jclass, jstring, jbyteArray, jstring, jstring);

/*
 * Class:     org_midway_MidWay
 * Method:    subscribe
 * Signature: (Ljava/lang/String;Lorg/midway/IEventListener;I)I
 */
JNIEXPORT jint JNICALL Java_org_midway_MidWay_subscribe
  (JNIEnv *, jclass, jstring, jobject, jint);

/*
 * Class:     org_midway_MidWay
 * Method:    recvevents
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_midway_MidWay_recvevents
  (JNIEnv *, jclass);

/*
 * Class:     org_midway_MidWay
 * Method:    log
 * Signature: (ILjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_midway_MidWay_log
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     org_midway_MidWay
 * Method:    setloglevel
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_org_midway_MidWay_setloglevel
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_midway_MidWay
 * Method:    openlog
 * Signature: (Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_org_midway_MidWay_openlog
  (JNIEnv *, jclass, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
