/*
 * This file was generated automatically by xsubpp version 1.9508 from the
 * contents of MidWay.xs. Do not edit this file, edit MidWay.xs instead.
 *
 *	ANY CHANGES MADE HERE WILL BE LOST!
 *
 */

#line 1 "MidWay.xs"
// -*- c -*- 
#include "EXTERN.h"
#include "perl.h"
#include "XSUB.h"

#include <MidWay.h>

static char * CVSId = "$Id: MidWay.xs,v 1.6 2004/06/17 09:51:41 eggestad Exp $";


static int
not_here(char *s)
{
    croak("%s not implemented on this architecture", s);
    return -1;
}

#define debug(fmt, ...) do { mwlog(MWLOG_DEBUG1, "%s(%d): " fmt, __FUNCTION__, __LINE__, ## __VA_ARGS__); } while(0)


static double
constant(char *name, int arg)
{
   debug ("adding constant %s", name);
    errno = 0;
    switch (*name) {
    case 'A':
	break;
    case 'B':
	break;
    case 'C':
	break;
    case 'D':
	break;
    case 'E':
	break;
    case 'F':
	if (strEQ(name, "FALSE"))
#ifdef FALSE
	    return FALSE;
#else
	    goto not_there;
#endif
	break;
    case 'G':
	break;
    case 'H':
	break;
    case 'I':
	break;
    case 'J':
	break;
    case 'K':
	break;
    case 'L':
	break;
    case 'M':
	if (strEQ(name, "MWCLIENT"))
#ifdef MWCLIENT
	    return MWCLIENT;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWCLIENTMASK"))
#ifdef MWCLIENTMASK
	    return MWCLIENTMASK;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWCONV"))
#ifdef MWCONV
	    return MWCONV;
#else
	    goto not_there;
#endif
	    if (strEQ(name, "MWEVSTRING"))
#ifdef MWEVSTRING
            return MWEVSTRING;
#else
            goto not_there;
#endif
	    if (strEQ(name, "MWEVGLOB"))
#ifdef MWEVGLOB
            return MWEVGLOB;
#else
            goto not_there;
#endif
	    if (strEQ(name, "MWEVREGEXP"))
#ifdef MWEVREGEXP
            return MWEVREGEXP;
#else
            goto not_there;
#endif
	    if (strEQ(name, "MWEVEREGEXP"))
#ifdef MWEVEREGEXP
            return MWEVEREGEXP;
#else
            goto not_there;
#endif
	if (strEQ(name, "MWFAIL"))
#ifdef MWFAIL
	    return MWFAIL;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWFASTPATH"))
#ifdef MWFASTPATH
	    return MWFASTPATH;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWGATEWAY"))
#ifdef MWGATEWAY
	    return MWGATEWAY;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWGATEWAYMASK"))
#ifdef MWGATEWAYMASK
	    return MWGATEWAYMASK;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWINDEXMASK"))
#ifdef MWINDEXMASK
	    return MWINDEXMASK;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWLOG_ALERT"))
#ifdef MWLOG_ALERT
	    return MWLOG_ALERT;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWLOG_DEBUG"))
#ifdef MWLOG_DEBUG
	    return MWLOG_DEBUG;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWLOG_DEBUG1"))
#ifdef MWLOG_DEBUG1
	    return MWLOG_DEBUG1;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWLOG_DEBUG2"))
#ifdef MWLOG_DEBUG2
	    return MWLOG_DEBUG2;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWLOG_DEBUG3"))
#ifdef MWLOG_DEBUG3
	    return MWLOG_DEBUG3;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWLOG_DEBUG4"))
#ifdef MWLOG_DEBUG4
	    return MWLOG_DEBUG4;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWLOG_ERROR"))
#ifdef MWLOG_ERROR
	    return MWLOG_ERROR;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWLOG_FATAL"))
#ifdef MWLOG_FATAL
	    return MWLOG_FATAL;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWLOG_INFO"))
#ifdef MWLOG_INFO
	    return MWLOG_INFO;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWLOG_WARNING"))
#ifdef MWLOG_WARNING
	    return MWLOG_WARNING;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWMAXNAMELEN"))
#ifdef MWMAXNAMELEN
	    return MWMAXNAMELEN;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWMAXSVCNAME"))
#ifdef MWMAXSVCNAME
	    return MWMAXSVCNAME;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWMORE"))
#ifdef MWMORE
	    return MWMORE;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWMULTIPLE"))
#ifdef MWMULTIPLE
	    return MWMULTIPLE;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWNOBLOCK"))
#ifdef MWNOBLOCK
	    return MWNOBLOCK;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWNOREPLY"))
#ifdef MWNOREPLY
	    return MWNOREPLY;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWNOTCLIENT"))
#ifdef MWNOTCLIENT
	    return MWNOTCLIENT;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWNOTIME"))
#ifdef MWNOTIME
	    return MWNOTIME;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWNOTRAN"))
#ifdef MWNOTRAN
	    return MWNOTRAN;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWSAFEPATH"))
#ifdef MWSAFEPATH
	    return MWSAFEPATH;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWSERVER"))
#ifdef MWSERVER
	    return MWSERVER;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWSERVERMASK"))
#ifdef MWSERVERMASK
	    return MWSERVERMASK;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWSERVERONLY"))
#ifdef MWSERVERONLY
	    return MWSERVERONLY;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWSERVICEMASK"))
#ifdef MWSERVICEMASK
	    return MWSERVICEMASK;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWSIGRST"))
#ifdef MWSIGRST
	    return MWSIGRST;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWSTDIO"))
#ifdef MWSTDIO
	    return MWSTDIO;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWSUCCESS"))
#ifdef MWSUCCESS
	    return MWSUCCESS;
#else
	    goto not_there;
#endif
	if (strEQ(name, "MWUNIQUE"))
#ifdef MWUNIQUE
	    return MWUNIQUE;
#else
	    goto not_there;
#endif
	break;
    case 'N':
	break;
    case 'O':
	break;
    case 'P':
	break;
    case 'Q':
	break;
    case 'R':
	break;
    case 'S':
	break;
    case 'T':
	if (strEQ(name, "TRUE"))
#ifdef TRUE
	    return TRUE;
#else
	    goto not_there;
#endif
	break;
    case 'U':
	if (strEQ(name, "UNASSIGNED"))
#ifdef UNASSIGNED
	    return UNASSIGNED;
#else
	    goto not_there;
#endif
	break;
    case 'V':
	break;
    case 'W':
	break;
    case 'X':
	break;
    case 'Y':
	break;
    case 'Z':
	break;
    }
    errno = EINVAL;
    return 0;

not_there:
    errno = ENOENT;
    return 0;
}

/************************************************************************
 *
 * task helpers, the SV point to the perl wrapper func, and the 
 * perlcalltaskwrapper call it. 

 * Whats happening here is almost pure magic, see perlcall(3)
 */

static SV * perl_task_dispatch = (SV*)NULL;
static SV * perl_event_dispatch = (SV*)NULL;

static int 
perlcalltaskwrapper(PTask pt)
{
   int rc;
   dSP ;
   int count ;

   ENTER ;
   SAVETMPS ;
   
   PUSHMARK(SP) ;
   XPUSHs(sv_2mortal(newSViv((IV)pt)));
   PUTBACK ;    	


   debug ("calling task wrapper with pt = %ld perl_task_dispatch = %p", pt, perl_task_dispatch);

   count = call_sv(perl_task_dispatch, G_SCALAR) ;  

   debug ("couht = %d", count);

   SPAGAIN ;

   if (count != 1)
      croak("Big trouble\n") ;
   
   rc = POPi;
   debug("rc = %d", rc);
   
   PUTBACK ;
   
   FREETMPS ;
   LEAVE ;
   return 0;
};

static void 
perl_event_hdl(int subid, char * event, char * data, int datalen)
{
   int rc;
   dSP ;
   
   debug("enter: subid %d event %s data \"%s\"", subid, event, data);
   ENTER ;
   SAVETMPS ;
   
   PUSHMARK(SP) ;
   XPUSHs(sv_2mortal(newSViv(subid)));
   XPUSHs(sv_2mortal(newSVpv(event, strlen(event))));
   XPUSHs(sv_2mortal(newSVpv(data, datalen)));
   PUTBACK ;    	


   debug ("calling EVENT wrapper");

   call_sv(perl_event_dispatch, G_DISCARD) ;  

   FREETMPS ;
   LEAVE ;
   debug("leave");
   return;
};

// THe module begin in ernest. 

#line 432 "MidWay.c"
XS(XS_MidWay_constant); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_constant)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: MidWay::constant(name, arg)");
    {
	char *	name = (char *)SvPV_nolen(ST(0));
	int	arg = (int)SvIV(ST(1));
	double	RETVAL;
	dXSTARG;

	RETVAL = constant(name, arg);
	XSprePUSH; PUSHn((double)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_MidWay_attach); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_attach)
{
    dXSARGS;
    if (items < 0 || items > 3)
	Perl_croak(aTHX_ "Usage: MidWay::attach(addr = NULL, name = NULL, flags = 0)");
    {
	char *	addr;
	char *	name;
	int	flags;
	int	RETVAL;
	dXSTARG;

	if (items < 1)
	    addr = NULL;
	else {
	    addr = (char *)SvPV_nolen(ST(0));
	}

	if (items < 2)
	    name = NULL;
	else {
	    name = (char *)SvPV_nolen(ST(1));
	}

	if (items < 3)
	    flags = 0;
	else {
	    flags = (int)SvIV(ST(2));
	}
#line 443 "MidWay.xs"
        if (addr && strlen(addr) == 0) addr = NULL;
	RETVAL = mwattach(addr, name, flags);
#line 484 "MidWay.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_MidWay_setcred); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_setcred)
{
    dXSARGS;
    if (items < 1)
	Perl_croak(aTHX_ "Usage: MidWay::setcred(authtype, username = NULL, ...)");
    {
	int	authtype = (int)SvIV(ST(0));
	char *	username;
#line 453 "MidWay.xs"
	STRLEN sl;
	int errorflag = 0;
	int rc;
#line 503 "MidWay.c"
	int	RETVAL;
	dXSTARG;

	if (items < 2)
	    username = NULL;
	else {
	    username = (char *)SvPV_nolen(ST(1));
	}
#line 457 "MidWay.xs"
	/*
		if (items > 0) {
			addr = (char *)SvPV(ST(0), sl);
			if (sl == 0) addr = NULL;
		}
		if (items > 1) {
			name = (char *)SvPV(ST(1), sl);
			if (sl == 0) name = NULL;
		}	
		if (items > 2)  {
			username = (char *)SvPV(ST(2), sl);
			if (sl == 0) username = NULL;
		}
		if (items > 3) {
			password = (char *)SvPV(ST(3), sl);
			if (sl == 0) password = NULL;
		}
		if (items > 4) {
			if (SvIOK(ST(4))) {
				flags = (int) SvIV(ST(4));
			} else if (SvNOK(ST(4))) {
				flags = (double) SvIV(ST(4));
			} else {
				errorflag = EINVAL;
			}
		}
	*/
	RETVAL = mwsetcred(authtype, username);
#line 541 "MidWay.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_MidWay_detach); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_detach)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: MidWay::detach()");
    {
	int	RETVAL;
	dXSTARG;
#line 492 "MidWay.xs"
	RETVAL = mwdetach();
#line 558 "MidWay.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_MidWay_listservices); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_listservices)
{
    dXSARGS;
    if (items < 0 || items > 1)
	Perl_croak(aTHX_ "Usage: MidWay::listservices(glob = \"*\")");
    SP -= items;
    {
	char *	glob;
#line 504 "MidWay.xs"
int flags = 0;
int rc, i;
char ** plist;
#line 577 "MidWay.c"

	if (items < 1)
	    glob = "*";
	else {
	    glob = (char *)SvPV_nolen(ST(0));
	}
#line 508 "MidWay.xs"
	rc = mwlistsvc(glob, &plist, flags);
        mwlog(MWLOG_DEBUG, "list = %d", rc);
        if (rc > 0) { 
	   EXTEND(SP, rc);
	   for (i = 0; i < rc; i++) {
	      PUSHs(sv_2mortal(newSVpv(plist[i], 0)));
	   };
	   free(plist);

	};
#line 595 "MidWay.c"
	PUTBACK;
	return;
    }
}

XS(XS_MidWay_call); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_call)
{
    dXSARGS;
    if (items < 1)
	Perl_croak(aTHX_ "Usage: MidWay::call(service, ...)");
    SP -= items;
    {
	char *	service = (char *)SvPV_nolen(ST(0));
#line 523 "MidWay.xs"
char * data = NULL;
STRLEN datalen = 0;
char * rdata = NULL;
STRLEN rdatalen = 0;
int apprc = 0;
int rc;
int flags = 0;
int error;
#line 619 "MidWay.c"
#line 532 "MidWay.xs"
	if (items > 1) {
		data = (char *)SvPV(ST(1), datalen);
		if (datalen == 0) data = NULL;
 	};
	if (items > 2) {
		flags = (int) SvIV(ST(2));
 	};
	rc = mwcall(service, data, datalen, &rdata, &rdatalen, &apprc, flags);

       	EXTEND(SP, 3);	
	PUSHs(sv_2mortal(newSViv(rc)));
	if (rdata != NULL)
		PUSHs(sv_2mortal(newSVpv(rdata, rdatalen)));	
	else 
		PUSHs(sv_2mortal(&PL_sv_undef));
	PUSHs(sv_2mortal(newSViv(apprc)));	

	if (rdata != NULL) mwfree(rdata);
#line 639 "MidWay.c"
	PUTBACK;
	return;
    }
}

XS(XS_MidWay_acall); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_acall)
{
    dXSARGS;
    if (items < 1)
	Perl_croak(aTHX_ "Usage: MidWay::acall(service, ...)");
    {
	char *	service = (char *)SvPV_nolen(ST(0));
#line 555 "MidWay.xs"
char * data;
STRLEN datalen = 0;
int flags;
int error;
#line 658 "MidWay.c"
	int	RETVAL;
	dXSTARG;
#line 560 "MidWay.xs"
	if (items > 1) {
		data = (char *)SvPV(ST(1), datalen);
		if (datalen == 0) data = NULL;
 	};
	if (items > 2) {
		flags = (int) SvIV(ST(2));
 	};
	RETVAL = mwacall(service, data, datalen, flags);
#line 670 "MidWay.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_MidWay_fetch); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_fetch)
{
    dXSARGS;
    if (items < 1 || items > 2)
	Perl_croak(aTHX_ "Usage: MidWay::fetch(handle, flags = 0)");
    SP -= items;
    {
	int	handle = (int)SvIV(ST(0));
	int	flags;
#line 577 "MidWay.xs"
char * rdata = NULL;
STRLEN rdatalen = 0;
int apprc = 0;
int rc;
int error;
#line 692 "MidWay.c"

	if (items < 2)
	    flags = 0;
	else {
	    flags = (int)SvIV(ST(1));
	}
#line 583 "MidWay.xs"
	if (items > 1) {
		flags = (int) SvIV(ST(1));
 	};
	rc = mwfetch(&handle, &rdata, &rdatalen, &apprc, flags);

	EXTEND(SP, 3);
	PUSHs(sv_2mortal(newSViv(rc)));
	PUSHs(sv_2mortal(newSVpv(rdata, rdatalen)));
	PUSHs(sv_2mortal(newSViv(apprc)));	

	if (rdata == NULL) mwfree(rdata);
#line 711 "MidWay.c"
	PUTBACK;
	return;
    }
}

XS(XS_MidWay_set_task_dispatch); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_set_task_dispatch)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: MidWay::set_task_dispatch(perlfunc)");
    {
	SV *	perlfunc = ST(0);
#line 604 "MidWay.xs"
	/* Take a copy of the callback */
    	if (perl_task_dispatch == (SV*)NULL)
    	    /* First time, so create a new SV */
    	    perl_task_dispatch = newSVsv(perlfunc) ;
    	else
    	    /* Been here before, so overwrite */
    	    SvSetSV(perl_task_dispatch, perlfunc) ;
	debug ("perl_task_dispatch = %p", perl_task_dispatch);
#line 734 "MidWay.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_MidWay_addtaskdelayed); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_addtaskdelayed)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: MidWay::addtaskdelayed(interval, delay)");
    {
	int	interval = (int)SvIV(ST(0));
	int	delay = (int)SvIV(ST(1));
	long	RETVAL;
	dXSTARG;
#line 618 "MidWay.xs"
	RETVAL = mwaddtaskdelayed(perlcalltaskwrapper, interval, delay);
#line 752 "MidWay.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_MidWay_waketask); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_waketask)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: MidWay::waketask(task)");
    {
	IV	task = (IV)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 626 "MidWay.xs"
	RETVAL = mwwaketask(task);
#line 770 "MidWay.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_MidWay_settaskinterval); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_settaskinterval)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: MidWay::settaskinterval(task, interval)");
    {
	IV	task = (IV)SvIV(ST(0));
	int	interval = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 635 "MidWay.xs"
	RETVAL = mwsettaskinterval (task, interval);
#line 789 "MidWay.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_MidWay_dotasks); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_dotasks)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: MidWay::dotasks()");
    {
#line 643 "MidWay.xs"
	mwdotasks();
#line 804 "MidWay.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_MidWay_set_event_dispatch); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_set_event_dispatch)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: MidWay::set_event_dispatch(perlfunc)");
    {
	SV *	perlfunc = ST(0);
#line 653 "MidWay.xs"
	/* Take a copy of the callback */
    	if (perl_event_dispatch == (SV*)NULL)
    	    /* First time, so create a new SV */
    	    perl_event_dispatch = newSVsv(perlfunc) ;
    	else
    	    /* Been here before, so overwrite */
    	    SvSetSV(perl_event_dispatch, perlfunc) ;
	debug ("perl_event_dispatch = %p", perl_event_dispatch);
#line 826 "MidWay.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_MidWay_event); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_event)
{
    dXSARGS;
    if (items < 1)
	Perl_croak(aTHX_ "Usage: MidWay::event(event, ...)");
    {
	char *	event = (char *)SvPV_nolen(ST(0));
#line 667 "MidWay.xs"
char * data;
STRLEN datalen, sl;
char * user;
char * name;
#line 844 "MidWay.c"
	int	RETVAL;
	dXSTARG;
#line 672 "MidWay.xs"
	if (items > 1) {
	   data = (char *)SvPV(ST(1), datalen);
	   if (datalen == 0) data = NULL;
	};
	if (items > 2) {
	   user = (char *)SvPV(ST(2), sl);
	   if (sl == 0) user = NULL;
 	};
	if (items > 3) {
	   name = (char *)SvPV(ST(3), sl);
	   if (sl == 0) name = NULL;
 	};


	RETVAL = mwevent(event, data, datalen, user, name);
	debug ("event \"%s\" data \"%s\"(%d) user %p name %p => %d", event, data, datalen, user, name, RETVAL);
#line 864 "MidWay.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_MidWay_subscribe); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_subscribe)
{
    dXSARGS;
    if (items != 3)
	Perl_croak(aTHX_ "Usage: MidWay::subscribe(pattern, flags, subid)");
    {
	char *	pattern = (char *)SvPV_nolen(ST(0));
	int	flags = (int)SvIV(ST(1));
	int	subid = (int)SvIV(ST(2));
	int	RETVAL;
	dXSTARG;
#line 697 "MidWay.xs"
	RETVAL = _mwsubscribe(pattern, subid, flags);
	debug ("subscribe \"%s\" subid %d flags %d => %d", pattern, subid, flags, RETVAL);
#line 885 "MidWay.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_MidWay_unsubscribe); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_unsubscribe)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: MidWay::unsubscribe(subid)");
    {
	int	subid = (int)SvIV(ST(0));
	int	RETVAL;
	dXSTARG;
#line 706 "MidWay.xs"
	RETVAL = mwunsubscribe(subid);
#line 903 "MidWay.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_MidWay_recvevents); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_recvevents)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: MidWay::recvevents()");
    {
#line 714 "MidWay.xs"
	mwrecvevents();
#line 918 "MidWay.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_MidWay_openlog); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_openlog)
{
    dXSARGS;
    if (items < 1 || items > 3)
	Perl_croak(aTHX_ "Usage: MidWay::openlog(progname, filepf = NULL, loglevel = MWLOG_INFO)");
    {
	char *	progname = (char *)SvPV_nolen(ST(0));
	char *	filepf;
	int	loglevel;

	if (items < 2)
	    filepf = NULL;
	else {
	    filepf = (char *)SvPV_nolen(ST(1));
	}

	if (items < 3)
	    loglevel = MWLOG_INFO;
	else {
	    loglevel = (int)SvIV(ST(2));
	}
#line 727 "MidWay.xs"
	if (strlen(filepf) == 0) filepf == NULL;

    	mwopenlog(progname, filepf, loglevel);
#line 949 "MidWay.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_MidWay_setloglevel); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_setloglevel)
{
    dXSARGS;
    if (items < 0 || items > 1)
	Perl_croak(aTHX_ "Usage: MidWay::setloglevel(level = -1)");
    {
	int	level;
	int	RETVAL;
	dXSTARG;

	if (items < 1)
	    level = -1;
	else {
	    level = (int)SvIV(ST(0));
	}
#line 738 "MidWay.xs"
	RETVAL = mwsetloglevel(level);
#line 972 "MidWay.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_MidWay_mw_log); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_mw_log)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: MidWay::mw_log(loglevel, logmesg)");
    {
	int	loglevel = (int)SvIV(ST(0));
	char *	logmesg = (char *)SvPV_nolen(ST(1));
#line 747 "MidWay.xs"
	mwlog(loglevel, logmesg);
#line 989 "MidWay.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_MidWay_begin); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_begin)
{
    dXSARGS;
    if (items < 1 || items > 2)
	Perl_croak(aTHX_ "Usage: MidWay::begin(sec, flags = 0)");
    {
	double	sec = (double)SvNV(ST(0));
	int	flags;
	int	RETVAL;
	dXSTARG;

	if (items < 2)
	    flags = 0;
	else {
	    flags = (int)SvIV(ST(1));
	}
#line 759 "MidWay.xs"
	RETVAL = mwbegin(sec, flags);
#line 1013 "MidWay.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_MidWay_commit); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_commit)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: MidWay::commit()");
    {
	int	RETVAL;
	dXSTARG;
#line 766 "MidWay.xs"
	RETVAL = mwcommit();
#line 1030 "MidWay.c"
    }
    XSRETURN(1);
}

XS(XS_MidWay_abort); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_abort)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: MidWay::abort()");
    {
	int	RETVAL;
	dXSTARG;
#line 771 "MidWay.xs"
	RETVAL = mwabort();
#line 1046 "MidWay.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_MidWay_systemstate); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_systemstate)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: MidWay::systemstate()");
    {
	int	RETVAL;
	dXSTARG;
#line 788 "MidWay.xs"
	RETVAL = _mwsystemstate();
#line 1063 "MidWay.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_MidWay_isattached); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_isattached)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: MidWay::isattached()");
    {
	int	RETVAL;
	dXSTARG;
#line 795 "MidWay.xs"
	RETVAL = _mw_isattached();
#line 1080 "MidWay.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_MidWay_incprovided); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_incprovided)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: MidWay::incprovided()");
    {
#line 803 "MidWay.xs"
void _mw_incprovided(void);
#line 1095 "MidWay.c"
#line 805 "MidWay.xs"
	_mw_incprovided();
#line 1098 "MidWay.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_MidWay_decprovided); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_decprovided)
{
    dXSARGS;
    if (items != 0)
	Perl_croak(aTHX_ "Usage: MidWay::decprovided()");
    {
#line 810 "MidWay.xs"
void _mw_decprovided(void);
#line 1112 "MidWay.c"
#line 812 "MidWay.xs"
	_mw_decprovided();
#line 1115 "MidWay.c"
    }
    XSRETURN_EMPTY;
}

XS(XS_MidWay_ipc_provide); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_ipc_provide)
{
    dXSARGS;
    if (items != 1)
	Perl_croak(aTHX_ "Usage: MidWay::ipc_provide(service)");
    {
	char *	service = (char *)SvPV_nolen(ST(0));
	int	RETVAL;
	dXSTARG;
#line 818 "MidWay.xs"
	RETVAL = _mw_ipc_provide(service,0);
#line 1132 "MidWay.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_MidWay_ipc_unprovide); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_ipc_unprovide)
{
    dXSARGS;
    if (items != 2)
	Perl_croak(aTHX_ "Usage: MidWay::ipc_unprovide(service, svcid)");
    {
	char *	service = (char *)SvPV_nolen(ST(0));
	int	svcid = (int)SvIV(ST(1));
	int	RETVAL;
	dXSTARG;
#line 827 "MidWay.xs"
	RETVAL = _mw_ipc_unprovide(service,svcid);
#line 1151 "MidWay.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_MidWay_forward); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_forward)
{
    dXSARGS;
    if (items < 1)
	Perl_croak(aTHX_ "Usage: MidWay::forward(service, ...)");
    {
	char *	service = (char *)SvPV_nolen(ST(0));
#line 835 "MidWay.xs"
char * data;
STRLEN datalen = 0;
int flags;
#line 1169 "MidWay.c"
	int	RETVAL;
	dXSTARG;
#line 839 "MidWay.xs"
	if (items > 1) {
		data = (char *)SvPV(ST(1), datalen);
		if (datalen == 0) data = NULL;
 	};
	if (items > 2) {
		flags = (int) SvIV(ST(2));
 	};
	RETVAL = mwforward(service, data, datalen, flags);
#line 1181 "MidWay.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_MidWay_reply); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_reply)
{
    dXSARGS;
    {
#line 854 "MidWay.xs"
char * data;
STRLEN datalen = 0;
int flags;
int rc;
int apprc;
#line 1198 "MidWay.c"
	int	RETVAL;
	dXSTARG;
#line 860 "MidWay.xs"
	if (items > 0) {
		data = (char *)SvPV(ST(0), datalen);
		if (datalen == 0) data = NULL;
 	} else {
		data = NULL;
		datalen = 0;
	}

	if (items > 1) {
		rc = (int) SvIV(ST(1));
 	} else {
		rc = MWSUCCESS;
	}

	if (items > 2) {
		apprc = (int) SvIV(ST(2));
	} else {
		apprc = 0;
	}

	if (items > 3) {
		flags = (int) SvIV(ST(3));
	} else {
		flags = 0;
	}

	RETVAL = mwreply(data, datalen, rc, apprc, flags);
#line 1229 "MidWay.c"
	XSprePUSH; PUSHi((IV)RETVAL);
    }
    XSRETURN(1);
}

XS(XS_MidWay_GetServiceRequest); /* prototype to pass -Wmissing-prototypes */
XS(XS_MidWay_GetServiceRequest)
{
    dXSARGS;
    if (items < 0 || items > 1)
	Perl_croak(aTHX_ "Usage: MidWay::GetServiceRequest(flags = 0)");
    SP -= items;
    {
	int	flags;
#line 895 "MidWay.xs"
mwsvcinfo * si;
#line 1246 "MidWay.c"

	if (items < 1)
	    flags = 0;
	else {
	    flags = (int)SvIV(ST(0));
	}
#line 897 "MidWay.xs"
	errno = 0;
	si = _mwGetServiceRequest(flags);
	if (si == NULL) {
		EXTEND(SP, 2);
		PUSHs(sv_2mortal(newSVpv("errorcode", 0)));
		PUSHs(sv_2mortal(newSViv(errno)));
	} else {
		EXTEND(SP, 22);
		PUSHs(sv_2mortal(newSVpv("handle", 0)));
		PUSHs(sv_2mortal(newSViv(si->handle)));
		PUSHs(sv_2mortal(newSVpv("data", 0)));
		PUSHs(sv_2mortal(newSVpv(si->data, si->datalen)));
		PUSHs(sv_2mortal(newSVpv("flags", 0)));
		PUSHs(sv_2mortal(newSViv(si->flags)));	
		PUSHs(sv_2mortal(newSVpv("service", 0)));
		PUSHs(sv_2mortal(newSVpv(si->service, 0)));	
		PUSHs(sv_2mortal(newSVpv("deadline", 0)));
		PUSHs(sv_2mortal(newSViv(si->deadline)));	
		PUSHs(sv_2mortal(newSVpv("clientid", 0)));
		PUSHs(sv_2mortal(newSViv(si->cltid)));
		PUSHs(sv_2mortal(newSVpv("serverid", 0)));
		PUSHs(sv_2mortal(newSViv(si->srvid)));
		PUSHs(sv_2mortal(newSVpv("serviceid", 0)));
		PUSHs(sv_2mortal(newSViv(si->svcid)));
		PUSHs(sv_2mortal(newSVpv("username", 0)));
		PUSHs(sv_2mortal(newSVpv(si->username, 0)));
		PUSHs(sv_2mortal(newSVpv("clientname", 0)));
		PUSHs(sv_2mortal(newSVpv(si->clientname, 0)));
		PUSHs(sv_2mortal(newSVpv("authentication", 0)));
		PUSHs(sv_2mortal(newSViv(si->authentication)));		
	}
#line 1285 "MidWay.c"
	PUTBACK;
	return;
    }
}

#ifdef __cplusplus
extern "C"
#endif
XS(boot_MidWay); /* prototype to pass -Wmissing-prototypes */
XS(boot_MidWay)
{
    dXSARGS;
    char* file = __FILE__;

    XS_VERSION_BOOTCHECK ;

        newXSproto("MidWay::constant", XS_MidWay_constant, file, "$$");
        newXSproto("MidWay::attach", XS_MidWay_attach, file, ";$$$");
        newXSproto("MidWay::setcred", XS_MidWay_setcred, file, "$;$@");
        newXSproto("MidWay::detach", XS_MidWay_detach, file, "");
        newXSproto("MidWay::listservices", XS_MidWay_listservices, file, ";$");
        newXSproto("MidWay::call", XS_MidWay_call, file, "$;@");
        newXSproto("MidWay::acall", XS_MidWay_acall, file, "$;@");
        newXSproto("MidWay::fetch", XS_MidWay_fetch, file, "$;$");
        newXSproto("MidWay::set_task_dispatch", XS_MidWay_set_task_dispatch, file, "$");
        newXSproto("MidWay::addtaskdelayed", XS_MidWay_addtaskdelayed, file, "$$");
        newXSproto("MidWay::waketask", XS_MidWay_waketask, file, "$");
        newXSproto("MidWay::settaskinterval", XS_MidWay_settaskinterval, file, "$$");
        newXSproto("MidWay::dotasks", XS_MidWay_dotasks, file, "");
        newXSproto("MidWay::set_event_dispatch", XS_MidWay_set_event_dispatch, file, "$");
        newXSproto("MidWay::event", XS_MidWay_event, file, "$;@");
        newXSproto("MidWay::subscribe", XS_MidWay_subscribe, file, "$$$");
        newXSproto("MidWay::unsubscribe", XS_MidWay_unsubscribe, file, "$");
        newXSproto("MidWay::recvevents", XS_MidWay_recvevents, file, "");
        newXSproto("MidWay::openlog", XS_MidWay_openlog, file, "$;$$");
        newXSproto("MidWay::setloglevel", XS_MidWay_setloglevel, file, ";$");
        newXSproto("MidWay::mw_log", XS_MidWay_mw_log, file, "$$");
        newXSproto("MidWay::begin", XS_MidWay_begin, file, "$;$");
        newXSproto("MidWay::commit", XS_MidWay_commit, file, "");
        newXSproto("MidWay::abort", XS_MidWay_abort, file, "");
        newXSproto("MidWay::systemstate", XS_MidWay_systemstate, file, "");
        newXSproto("MidWay::isattached", XS_MidWay_isattached, file, "");
        newXSproto("MidWay::incprovided", XS_MidWay_incprovided, file, "");
        newXSproto("MidWay::decprovided", XS_MidWay_decprovided, file, "");
        newXSproto("MidWay::ipc_provide", XS_MidWay_ipc_provide, file, "$");
        newXSproto("MidWay::ipc_unprovide", XS_MidWay_ipc_unprovide, file, "$$");
        newXSproto("MidWay::forward", XS_MidWay_forward, file, "$;@");
        newXSproto("MidWay::reply", XS_MidWay_reply, file, ";@");
        newXSproto("MidWay::GetServiceRequest", XS_MidWay_GetServiceRequest, file, ";$");

    /* Initialisation Section */

#line 934 "MidWay.xs"
	debug ("Boot block");
        _mw_register_event_handler(perl_event_hdl);

#line 1342 "MidWay.c"

    /* End of Initialisation Section */

    XSRETURN_YES;
}

